-- This file contains a proof of Lemma 3.7. This proof is done by simply computing a Grobner basis for the ideal generated by the minors G_n
-- We then check that the resulting Grobner basis is just given by G_n
-- The main functions involved here can all be found in the file PfaffianPhyloNets.m2

load "PfaffianPhyloNets.m2"

-- This makes a hashtable whose keys are values of n from 5 to 11 and whose values are the rings X_n
xRings = new MutableHashTable from apply(toList(5..11), n -> n => xRing n)

-- This makes a hashtable whose keys are values of n from 5 to 11 and whose values are the ideals generated by the minors G_n
pfIdeals = new MutableHashTable from apply(toList(5..11), n -> n => pfaffianDetIdeal(n, xRings#n))


-- This loops through all values of n from 5 to 11 and checks that G_n is a Grobner basis for the ideal it generates with respect to the constructed term order
for n from 5 to 11 list(

    X = xRings#n;

    G = flatten entries gens pfIdeals#n;

    gbForIdeal = flatten entries gens gb pfIdeals#n;

    all(G, g -> member(g, gbForIdeal) or member(-g, gbForIdeal)) and all(gbForIdeal, f -> member(f, G) or member(-f, G))
    )

